# Sets the active profile to 'test'
spring.profiles.active=test
# Sets the application name
spring.application.name=projetoJava

# Configuração de conexão com o MongoDB Local
spring.data.mongodb.uri=mongodb://localhost:27017/erp_db